Detect if a service update fails
`docker service update` will exit with `1` and write something like
`service update paused: update paused due to failure or early termination of task ...`
to stderr if the updated service fails to start or remains unhealthy.

With this change this event appears in the logs explicitly.

diff --git a/shepherd b/shepherd
--- a/shepherd
+++ b/shepherd
@@ -44,7 +44,9 @@ update_services() {
       else
         logger "Trying to update service $name with image $image" "true"
 
-        docker service update "$name" $detach_option $registry_auth $no_resolve_image_flag --image="$image" > /dev/null
+        if ! docker service update "$name" $detach_option $registry_auth $no_resolve_image_flag --image="$image" > /dev/null; then
+          logger "Service $name update failed!"
+        fi
 
         previousImage=$(docker service inspect "$name" -f '{{.PreviousSpec.TaskTemplate.ContainerSpec.Image}}')
         currentImage=$(docker service inspect "$name" -f '{{.Spec.TaskTemplate.ContainerSpec.Image}}')
